# Generated by Django 2.0.7 on 2021-01-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default=True, max_length=120),
            preserve_default=False,
        ),
    ]
